#!/bin/bash


[ $(pamixer --get-mute) = true ] && echo "^c#D08770^"婢 && exit

vol="$(pamixer --get-volume)"

if [ "$vol" -gt "70" ]; then
	icon="墳"
elif [ "$vol" -gt "30" ]; then
	icon="奔"
elif [ "$vol" -gt "0" ]; then
	icon=""
else
		echo "^c#D08770^"婢 $vol% && exit
fi

echo "^c#D08770^$icon $vol%"
